export const RENTERS_LIST_REQUEST = 'RENTERS_LIST_REQUEST'
export const RENTERS_LIST_SUCCESS = 'RENTERS_LIST_SUCCESS'
export const RENTERS_LIST_FAIL = 'RENTERS_LIST_FAIL'

export const RENTER_UPDATE_REQUEST = 'RENTER_UPDATE_REQUEST'
export const RENTER_UPDATE_SUCCESS = 'RENTER_UPDATE_SUCCESS'
export const RENTER_UPDATE_FAIL = 'RENTER_UPDATE_FAILS'
export const RENTER_UPDATE_RESET = 'RENTER_UPDATE_RESETS'


export const RENTER_DETAILS_REQUEST = 'RENTER_DETAILS_REQUEST'
export const RENTER_DETAILS_SUCCESS = 'RENTER_DETAILS_SUCCESS'
export const RENTER_DETAILS_FAIL = 'RENTER_DETAILS_FAIL'
export const RENTER_DETAILS_RESET = 'RENTER_DETAILS_RESET'

