# Generated by Django 4.0.1 on 2022-02-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
