# Generated by Django 4.0.1 on 2022-02-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_renter_water_rooms_electric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='renter_id',
        ),
        migrations.RemoveField(
            model_name='water',
            name='renter_id',
        ),
        migrations.DeleteModel(
            name='Electric',
        ),
        migrations.DeleteModel(
            name='Renter',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Water',
        ),
    ]
