# Generated by Django 4.0.1 on 2022-02-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_electric_utilities_electricy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilities',
            old_name='electricy',
            new_name='electricty',
        ),
    ]
