# Generated by Django 4.0.1 on 2022-02-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_electricy_utilities_electricty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilities',
            name='electrict',
        ),
    ]
