# Generated by Django 4.0.1 on 2022-02-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_utilities_electrictybill_utilities_trashbill_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilities',
        ),
    ]
