# Generated by Django 4.0.1 on 2022-02-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='renter_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
