# Generated by Django 4.0.1 on 2022-02-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='renter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.renter'),
        ),
    ]
