# Generated by Django 4.0.1 on 2022-02-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_apartment_renter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
