# Generated by Django 4.0.1 on 2022-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_apartment_phone_apartment_renter_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/product_placeholder.png', null=True, upload_to=''),
        ),
    ]
