# Generated by Django 4.0.1 on 2022-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_renterpayments_electric'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterpayments',
            name='room_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
