# Generated by Django 4.0.1 on 2022-03-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_renterpayments_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renterpayments',
            name='renter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
