# Generated by Django 4.0.1 on 2022-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_renterpayments_renter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterpayments',
            name='renter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
