# Generated by Django 4.0.1 on 2022-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_renterpayments_renter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('room_number', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('rentIsPaid', models.BooleanField(default=False)),
                ('rentIsPaidAt', models.DateTimeField(blank=True, null=True)),
                ('water', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('waterIsPaid', models.BooleanField(default=False)),
                ('waterIsPaidAt', models.DateTimeField(blank=True, null=True)),
                ('electric', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('electricIsPaid', models.BooleanField(default=False)),
                ('electricIsPaidAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
