# Generated by Django 4.0.1 on 2022-03-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_renterpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenterPayments',
        ),
    ]
