# Generated by Django 4.0.1 on 2022-03-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_review_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenterPayment',
        ),
    ]
