# Generated by Django 3.2.12 on 2022-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_delete_renterpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='frontend/build/product_placeholder.png', null=True, upload_to=''),
        ),
    ]
