# Generated by Django 3.2.12 on 2022-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/product_placeholder.png', null=True, upload_to=''),
        ),
    ]
